#ifndef STATE_H
#define STATE_H

typedef enum GAME_STATE {
  BOOTSTRAP,
  MENU,
  HELP,
  CHARACTER_SELECTION_MENU,
  GAME_IN_PROGRESS,
  GAME_PAUSED,
  GAME_OVER
} GAME_STATE;

GAME_STATE CURRENT_STATE = MENU;

extern GAME_STATE CURRENT_STATE;

#endif